/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "RepeatPeriod": {                                "en": "e.g. 1Y for 1 year",                              "de": "z.B. 1Y für 1 Jahr",                              "ru": "например 1Y на 1 год",                            "pt": "por exemplo. 1Y por 1 ano",                       "nl": "b.v. 1Y voor 1 jaar",                             "fr": "par exemple. 1Y pour 1 an",                       "it": "per esempio. 1Y per 1 anno",                      "es": "p.ej. 1Y por 1 año",                              "pl": "na przykład 1Y na 1 rok",                         "zh-cn": "例如一年 1Y"},
    "addCountdown": {                                "en": "Add countdown",                                   "de": "Countdown hinzufügen",                            "ru": "Добавить обратный отсчет",                        "pt": "Adicionar contagem regressiva",                   "nl": "Aftellen toevoegen",                              "fr": "Ajouter un compte à rebours",                     "it": "Aggiungi il conto alla rovescia",                 "es": "Agregar cuenta regresiva",                        "pl": "Dodaj odliczanie",                                "zh-cn": "添加倒计时"},
    "autodelete": {                                  "en": "Delete countdown when end is reached",            "de": "Countdown löschen wenn Zeitpunkt erreicht wurde", "ru": "Удалить обратный отсчет, когда достигнут конец",  "pt": "Excluir contagem regressiva quando o fim é atingido", "nl": "Wis Countdown als het einde is bereikt",          "fr": "Supprimer le compte à rebours lorsque la fin est atteinte", "it": "Elimina il conto alla rovescia quando viene raggiunta la fine", "es": "Eliminar cuenta atrás cuando se llega al final",  "pl": "Usuń odliczanie po osiągnięciu końca",            "zh-cn": "达到结束时删除倒计时"},
    "dateFormat": {                                  "en": "Date format",                                     "de": "Datumsformat",                                    "ru": "Формат даты",                                     "pt": "Formato de data",                                 "nl": "Datumnotatie",                                    "fr": "Format de date",                                  "it": "Formato data",                                    "es": "Formato de fecha",                                "pl": "Format daty",                                     "zh-cn": "日期格式"},
    "endDate": {                                     "en": "End date",                                        "de": "Enddatum",                                        "ru": "Дата окончания",                                  "pt": "Data final",                                      "nl": "Einddatum",                                       "fr": "Date de fin",                                     "it": "Data di fine",                                    "es": "Fecha final",                                     "pl": "Data zakonczenia",                                "zh-cn": "结束日期"},
    "inWordsLong": {                                 "en": "In words (long)",                                 "de": "In Worten (lang)",                                "ru": "Словами (долго)",                                 "pt": "Em palavras (longa)",                             "nl": "In woorden (lang)",                               "fr": "En mots (long)",                                  "it": "In parole (lungo)",                               "es": "En palabras (largo)",                             "pl": "Słownie (długo)",                                 "zh-cn": "用词（长）"},
    "inWordsShort": {                                "en": "In words (short)",                                "de": "In Worten (kurz)",                                "ru": "Словами (коротко)",                               "pt": "Em palavras (curta)",                             "nl": "In woorden (kort)",                               "fr": "En mots (court)",                                 "it": "In parole (breve)",                               "es": "En palabras",                                     "pl": "Słowami (krótki)",                                "zh-cn": "用文字（短）"},
    "settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "настройки",                                       "pt": "Definições",                                      "nl": "Instellingen",                                    "fr": "Paramètres",                                      "it": "impostazioni",                                    "es": "Configuraciones",                                 "pl": "Ustawienia",                                      "zh-cn": "设定值"},
    "tablecontent": {                                "en": "Show these fields in table:",                     "de": "Folgende Felder in Tabelle anzeigen:",            "ru": "Показать эти поля в таблице:",                    "pt": "Mostrar estes campos na tabela:",                 "nl": "Toon deze velden in de tabel:",                   "fr": "Afficher ces champs dans le tableau:",            "it": "Mostra questi campi nella tabella:",              "es": "Mostrar estos campos en la tabla:",               "pl": "Pokaż te pola w tabeli:",                         "zh-cn": "在表格中显示这些字段："},
    "totalNoOfDays": {                               "en": "Total number of days",                            "de": "Gesamtanzahl Tagen",                              "ru": "Общее количество дней",                           "pt": "Número total de dias",                            "nl": "Totaal aantal dagen",                             "fr": "Nombre total de jours",                           "it": "Numero totale di giorni",                         "es": "Numero total de dias",                            "pl": "Całkowita liczba dni",                            "zh-cn": "总天数"},
    "totalNoOfHours": {                              "en": "Total number of hours",                           "de": "Gesamtanzahl Stunden",                            "ru": "Общее количество часов",                          "pt": "Número total de horas",                           "nl": "Totaal aantal uren",                              "fr": "Nombre total d'heures",                           "it": "Numero totale di ore",                            "es": "Numero total de horas",                           "pl": "Całkowita liczba godzin",                         "zh-cn": "总小时数"},
    "totalNoOfWeeks": {                              "en": "Total number of weeks",                           "de": "Gesamtanzahl Wochen",                             "ru": "Общее количество недель",                         "pt": "Número total de semanas",                         "nl": "Totaal aantal weken",                             "fr": "Nombre total de semaines",                        "it": "Numero totale di settimane",                      "es": "Número total de semanas",                         "pl": "Całkowita liczba tygodni",                        "zh-cn": "总周数"},
};